name: GitHub Workflow Testing

on:
  pull_request:
    types: [opened, reopened, closed]
  delete:

jobs:
  configure-project-issue:
    runs-on: [ubuntu-latest]
    name: GitHub Workflow Testing
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: ./
